"""Build and serve the interactive Wikipedia trajectory visualization."""

from __future__ import annotations

import argparse
import functools
import json
import shutil
import sys
import webbrowser
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from importlib.resources import files
from pathlib import Path

from tkg.visualization.exporter import build_visualization_data


MARKER = ".tkg-visualization"
ASSET_NAMES = ("index.html", "styles.css", "app.js")


def build_site(data: dict, output_dir: str, *, overwrite: bool = False) -> Path:
    output = Path(output_dir).resolve()
    if output.exists() and any(output.iterdir()):
        generated = (output / MARKER).is_file()
        if not generated and not overwrite:
            raise ValueError(
                f"refusing to write into non-generated directory {output}; choose another "
                "--output-dir or pass --overwrite"
            )
    output.mkdir(parents=True, exist_ok=True)
    static = files("tkg.visualization").joinpath("static")
    for name in ASSET_NAMES:
        source = static.joinpath(name)
        with source.open("rb") as input_fh, (output / name).open("wb") as output_fh:
            shutil.copyfileobj(input_fh, output_fh)
    with (output / "data.json").open("w", encoding="utf-8") as fh:
        json.dump(data, fh, ensure_ascii=False, separators=(",", ":"))
    (output / MARKER).write_text("generated by tkg-visualize\n", encoding="utf-8")
    return output


class _QuietHandler(SimpleHTTPRequestHandler):
    def log_message(self, format: str, *args) -> None:
        print(f"[http] {self.address_string()} {format % args}")


def serve(output: Path, host: str, port: int, *, open_browser: bool) -> None:
    handler = functools.partial(_QuietHandler, directory=str(output))
    server = ThreadingHTTPServer((host, port), handler)
    actual_port = server.server_address[1]
    browser_host = "127.0.0.1" if host in {"0.0.0.0", "::"} else host
    url = f"http://{browser_host}:{actual_port}/"
    print(f"[serve] {url}")
    if open_browser:
        webbrowser.open(url)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\n[serve] stopped")
    finally:
        server.server_close()


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build and serve an interactive Wikipedia page graph + LLM trajectory viewer"
    )
    parser.add_argument("--cache", default="wikipedia_snapshot.db")
    parser.add_argument("--results", default="temporal_results.jsonl")
    parser.add_argument("--output-dir", default=".tkg_visualization")
    parser.add_argument(
        "--include-linked-stubs", action=argparse.BooleanOptionalAction, default=True,
        help="include unresolved hyperlink targets as nodes (enabled by default)",
    )
    parser.add_argument("--max-stub-nodes", type=int, default=2000)
    parser.add_argument("--excerpt-chars", type=int, default=700)
    parser.add_argument("--build-only", action="store_true")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8765)
    parser.add_argument("--no-browser", action="store_true")
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()
    if args.max_stub_nodes < 0 or args.excerpt_chars < 100:
        parser.error("--max-stub-nodes must be >= 0 and --excerpt-chars must be >= 100")
    if not 0 <= args.port <= 65535:
        parser.error("--port must be between 0 and 65535")
    try:
        data = build_visualization_data(
            args.cache,
            args.results,
            include_linked_stubs=args.include_linked_stubs,
            max_stub_nodes=args.max_stub_nodes,
            excerpt_chars=args.excerpt_chars,
        )
        output = build_site(data, args.output_dir, overwrite=args.overwrite)
    except (FileNotFoundError, ValueError) as exc:
        print(f"[error] {exc}", file=sys.stderr)
        return 2
    print(
        f"[build] {output} | nodes={len(data['graph']['nodes'])} "
        f"edges={len(data['graph']['edges'])} trajectories={len(data['trajectories'])}"
    )
    if args.build_only:
        return 0
    serve(output, args.host, args.port, open_browser=not args.no_browser)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
